use crate::messages::{
    adjust_periodic_event_stream::{
        AdjustPeriodicEventStreamRequest, AdjustPeriodicEventStreamResponse,
    },
    afr_signal::{AFRRSignalRequest, AFRRSignalResponse},
    authorize::{AuthorizeRequest, AuthorizeResponse},
    battery_swap::{BatterySwapRequest, BatterySwapResponse},
    boot_notification::{BootNotificationRequest, BootNotificationResponse},
    cancel_reservation::{CancelReservationRequest, CancelReservationResponse},
    certificate_signed::{CertificateSignedRequest, CertificateSignedResponse},
    change_availability::{ChangeAvailabilityRequest, ChangeAvailabilityResponse},
    change_transaction_tariff::{ChangeTransactionTariffRequest, ChangeTransactionTariffResponse},
    clear_cache::{ClearCacheRequest, ClearCacheResponse},
    clear_charging_profile::{ClearChargingProfileRequest, ClearChargingProfileResponse},
    clear_der_control::{ClearDERControlRequest, ClearDERControlResponse},
    clear_display_message::{ClearDisplayMessageRequest, ClearDisplayMessageResponse},
    clear_tariffs::{ClearTariffsRequest, ClearTariffsResponse},
    clear_variable_monitoring::{ClearVariableMonitoringRequest, ClearVariableMonitoringResponse},
    cleared_charging_limit::{ClearedChargingLimitRequest, ClearedChargingLimitResponse},
    close_periodic_event_stream::{
        ClosePeriodicEventStreamRequest, ClosePeriodicEventStreamResponse,
    },
    cost_updated::{CostUpdatedRequest, CostUpdatedResponse},
    customer_information::{CustomerInformationRequest, CustomerInformationResponse},
    data_transfer::{DataTransferRequest, DataTransferResponse},
    delete_certificate::{DeleteCertificateRequest, DeleteCertificateResponse},
    firmware_status_notification::{
        FirmwareStatusNotificationRequest, FirmwareStatusNotificationResponse,
    },
    get_15118_ev_certificate::{Get15118EVCertificateRequest, Get15118EVCertificateResponse},
    get_base_report::{GetBaseReportRequest, GetBaseReportResponse},
    get_certificate_chain_status::{
        GetCertificateChainStatusRequest, GetCertificateChainStatusResponse,
    },
    get_certificate_status::{GetCertificateStatusRequest, GetCertificateStatusResponse},
    get_charging_profiles::{GetChargingProfilesRequest, GetChargingProfilesResponse},
    get_composite_schedule::{GetCompositeScheduleRequest, GetCompositeScheduleResponse},
    get_der_control::{GetDERControlRequest, GetDERControlResponse},
    get_display_messages::{GetDisplayMessagesRequest, GetDisplayMessagesResponse},
    get_installed_certificate_ids::{
        GetInstalledCertificateIdsRequest, GetInstalledCertificateIdsResponse,
    },
    get_local_list_version::{GetLocalListVersionRequest, GetLocalListVersionResponse},
    get_log::{GetLogRequest, GetLogResponse},
    get_monitoring_report::{GetMonitoringReportRequest, GetMonitoringReportResponse},
    get_periodic_event_stream::{GetPeriodicEventStreamRequest, GetPeriodicEventStreamResponse},
    get_report::{GetReportRequest, GetReportResponse},
    get_tariffs::{GetTariffsRequest, GetTariffsResponse},
};

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
#[serde(untagged)]
pub enum OcppMessage {
    AdjustPeriodicEventStreamRequest(AdjustPeriodicEventStreamRequest),
    AdjustPeriodicEventStreamResponse(AdjustPeriodicEventStreamResponse),
    AFRRSignalRequest(AFRRSignalRequest),
    AFRRSignalResponse(AFRRSignalResponse),
    AuthorizeRequest(AuthorizeRequest),
    AuthorizeResponse(Box<AuthorizeResponse>),
    BatterySwapRequest(BatterySwapRequest),
    BatterySwapResponse(BatterySwapResponse),
    BootNotificationRequest(BootNotificationRequest),
    BootNotificationResponse(BootNotificationResponse),
    CancelReservationRequest(CancelReservationRequest),
    CancelReservationResponse(CancelReservationResponse),
    CertificateSignedRequest(CertificateSignedRequest),
    CertificateSignedResponse(CertificateSignedResponse),
    ChangeAvailabilityRequest(ChangeAvailabilityRequest),
    ChangeAvailabilityResponse(ChangeAvailabilityResponse),
    ChangeTransactionTariffRequest(ChangeTransactionTariffRequest),
    ChangeTransactionTariffResponse(ChangeTransactionTariffResponse),
    ClearCacheRequest(ClearCacheRequest),
    ClearCacheResponse(ClearCacheResponse),
    ClearChargingProfileRequest(ClearChargingProfileRequest),
    ClearChargingProfileResponse(ClearChargingProfileResponse),
    ClearDERControlRequest(ClearDERControlRequest),
    ClearDERControlResponse(ClearDERControlResponse),
    ClearDisplayMessageRequest(ClearDisplayMessageRequest),
    ClearDisplayMessageResponse(ClearDisplayMessageResponse),
    ClearTariffsRequest(ClearTariffsRequest),
    ClearTariffsResponse(ClearTariffsResponse),
    ClearVariableMonitoringRequest(ClearVariableMonitoringRequest),
    ClearVariableMonitoringResponse(ClearVariableMonitoringResponse),
    ClearedChargingLimitRequest(ClearedChargingLimitRequest),
    ClearedChargingLimitResponse(ClearedChargingLimitResponse),
    ClosePeriodicEventStreamRequest(ClosePeriodicEventStreamRequest),
    ClosePeriodicEventStreamResponse(ClosePeriodicEventStreamResponse),
    CostUpdatedRequest(CostUpdatedRequest),
    CostUpdatedResponse(CostUpdatedResponse),
    CustomerInformationRequest(CustomerInformationRequest),
    CustomerInformationResponse(CustomerInformationResponse),
    DataTransferRequest(DataTransferRequest),
    DataTransferResponse(DataTransferResponse),
    DeleteCertificateRequest(DeleteCertificateRequest),
    DeleteCertificateResponse(DeleteCertificateResponse),
    FirmwareStatusNotificationRequest(FirmwareStatusNotificationRequest),
    FirmwareStatusNotificationResponse(FirmwareStatusNotificationResponse),
    Get15118EVCertificateRequest(Get15118EVCertificateRequest),
    Get15118EVCertificateResponse(Get15118EVCertificateResponse),
    GetBaseReportRequest(GetBaseReportRequest),
    GetBaseReportResponse(GetBaseReportResponse),
    GetCertificateChainStatusRequest(GetCertificateChainStatusRequest),
    GetCertificateChainStatusResponse(GetCertificateChainStatusResponse),
    GetCertificateStatusRequest(GetCertificateStatusRequest),
    GetCertificateStatusResponse(GetCertificateStatusResponse),
    GetChargingProfilesRequest(GetChargingProfilesRequest),
    GetChargingProfilesResponse(GetChargingProfilesResponse),
    GetCompositeScheduleRequest(GetCompositeScheduleRequest),
    GetCompositeScheduleResponse(GetCompositeScheduleResponse),
    GetDERControlRequest(GetDERControlRequest),
    GetDERControlResponse(GetDERControlResponse),
    GetDisplayMessagesRequest(GetDisplayMessagesRequest),
    GetDisplayMessagesResponse(GetDisplayMessagesResponse),
    GetInstalledCertificateIdsRequest(GetInstalledCertificateIdsRequest),
    GetInstalledCertificateIdsResponse(GetInstalledCertificateIdsResponse),
    GetLocalListVersionRequest(GetLocalListVersionRequest),
    GetLocalListVersionResponse(GetLocalListVersionResponse),
    GetLogRequest(GetLogRequest),
    GetLogResponse(GetLogResponse),
    GetMonitoringReportRequest(GetMonitoringReportRequest),
    GetMonitoringReportResponse(GetMonitoringReportResponse),
    GetPeriodicEventStreamRequest(GetPeriodicEventStreamRequest),
    GetPeriodicEventStreamResponse(GetPeriodicEventStreamResponse),
    GetReportRequest(GetReportRequest),
    GetReportResponse(GetReportResponse),
    GetTariffsRequest(GetTariffsRequest),
    GetTariffsResponse(GetTariffsResponse),
}
